API
SamueleFacenda/activitn pull request #1
Opened 2024-10-31 14:36 UTC by ThomasCetto

- Added APIs defined in the swagger file
- Changed id's type from integer to string in  the swagger file
- Added  mongodb, mongoose and swagger dependencies
- Created a small app to test the APIs
- Added to the swagger and implemented, 2 APIs to add and remove users from events
- Added .gitignore

2024-10-31 14:48 UTC, SamueleFacenda commented
Riesci a rinominare un po' i commit, [così](https://www.conventionalcommits.org/en/v1.0.0/)? Basta che fai un rebase interactive e metti `reword` al posto di `pick` per i commit che vuoi modificare  e salvi, poi ti fa cambiare i commit uno alla volta

2024-10-31 14:49 UTC, SamueleFacenda approved these changes
lgtm

2024-11-01 11:09 UTC, SamueleFacenda requested changes
Refactor dei commit messages

2024-11-04 10:54 UTC, ThomasCetto commented
cosi' va bene? breaking changes non credo ce ne fossero, dato che prima non c'era proprio nulla

2024-11-04 10:59 UTC, merged